title = "Bihacker Viktor"
baseURL = "https://viktorbihacker.netlify.com/"
languageCode = "en-us"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  description = "Junior Sofware Developer"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/HackerVik"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/viktor-bihacker-00a2b3196/"
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/screen.jpg"
  recent_posts_number = 3
